name: Chromatic Visual Testing
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - '.storybook/**'

# Add permissions block
permissions:
  contents: read
  pull-requests: write # This allows the action to comment on PRs

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
      - name: Comment PR
        if: ${{ steps.chromatic.outputs.storybookUrl }}
        uses: actions/github-script@v6
        with:
          script: |
            const storybookUrl = '${{ steps.chromatic.outputs.storybookUrl }}';
            const buildUrl = '${{ steps.chromatic.outputs.buildUrl }}';
            
            const message = `## Visual Changes Detected 🎨
            
            Changes have been detected in your Storybook components.
            
            ### Review Changes
            📸 [View Visual Comparison](${buildUrl}/review) - See side-by-side & diff views
            🔍 [View Build Details](${buildUrl}) - See all component changes
            📚 [View Storybook](${storybookUrl}) - Preview the latest version
            
            ### What to Look For
            - Check component layout and spacing
            - Verify color changes are intentional
            - Review text content updates
            - Ensure responsive behavior
            
            Click the "Visual Comparison" link to see detailed before/after views of all changes.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });